apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: beta-powerbiz
  region: ap-southeast-1
vpc:
  id: "vpc-0710f4c9eeaea01b2"
  cidr: "10.49.0.0/16"
  subnets:
    private:
      ap-southeast-1a:
          id: "subnet-0c5e27b6fc964ee15"
          cidr: "10.49.128.0/18"
      ap-southeast-1b:
          id: "subnet-050ae6cf92c673cfe"
          cidr: "10.49.192.0/18"
    public:
      prod-sg-pub-snet-1a:
          id: "subnet-06367bff1a44ecef1"
          cidr: "10.49.0.0/18"
      prod-sg-pub-snet-1b:
          id: "subnet-0c994e64547808c98"
          cidr: "10.49.64.0/18"