controller:
  service:
    targetPorts:
      http: http
      https: http
      
    annotations: #https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/
      # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:939923956045:certificate/1bd9d74b-bdc4-4215-8e81-cc18f1c053b2
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      # service.beta.kubernetes.io/aws-load-balancer-name: beta-powerbiz-nlb
      #service.beta.kubernetes.io/aws-load-balancer-subnets:
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      #service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: 

  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  # ingressClassByName: true