apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: alpha
  region: ap-southeast-1



# nodeGroups:
# - name: spot-t3-large-ng
#   amiFamily: Bottlerocket
#   instanceType: t3.large
#   desiredCapacity: 1
#   minSize: 0
#   maxSize: 10
#   # volumeSize: 80
#   labels:
#     application-node: "true"
#   spot: true
#   kubeletExtraConfig:
#     kubeReserved:
#         cpu: "300m"
#         memory: "300Mi"
#         ephemeral-storage: "1Gi"
#     kubeReservedCgroup: "/kube-reserved"
#     systemReserved:
#         cpu: "300m"
#         memory: "300Mi"
#         ephemeral-storage: "1Gi"
#     evictionHard:
#         memory.available:  "200Mi"
#         nodefs.available: "10%"
#     featureGates:
#         RotateKubeletServerCertificate: true # has to be enabled, otherwise it will be disabled

managedNodeGroups:
- name: mng1
  instanceType: t3.medium
  minSize: 0
  maxSize: 5
  desiredCapacity: 1 
  amiFamily: Bottlerocket
  bottlerocket:
    enableAdminContainer: true
    settings:
      motd: "Hello, eksctl!"
      kubernetes:
        #allowed-unsafe-sysctls: ["net.core.somaxconn","net.ipv4.ip_local_port_range"]
        kubeReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            RotateKubeletServerCertificate: true # has to be enabled, otherwise it will be disabled 