apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: beta
  region: ap-southeast-1
  version: "1.21"

#shared vpc with beta
vpc:
  id: "vpc-0710f4c9eeaea01b2"
  cidr: "10.49.0.0/16"
  subnets:
    private:
      ap-southeast-1a:
          id: "subnet-0c5e27b6fc964ee15"
          cidr: "10.49.128.0/18"
      ap-southeast-1b:
          id: "subnet-050ae6cf92c673cfe"
          cidr: "10.49.192.0/18"
    public:
      prod-sg-pub-snet-1a:
          id: "subnet-06367bff1a44ecef1"
          cidr: "10.49.0.0/18"
      prod-sg-pub-snet-1b:
          id: "subnet-0c994e64547808c98"
          cidr: "10.49.64.0/18"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

addons:
- name: vpc-cni

cloudWatch:
  clusterLogging: 
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 365

karpenter:
  version: '0.7.0'
  createServiceAccount: true # default is false  

# nodeGroups:
# #public ondemand
#   - name: public-ondemand-t3-small-ng
#     amiFamily: Bottlerocket
#     instanceType: m5.xlarge
#     desiredCapacity: 10
#     minSize: 0
#     maxSize: 10
#     volumeSize: 80
#     labels:
#       application-node: true
#     kubeletExtraConfig:
#         kubeReserved:
#             cpu: "300m"
#             memory: "300Mi"
#             ephemeral-storage: "1Gi"
#         kubeReservedCgroup: "/kube-reserved"
#         systemReserved:
#             cpu: "300m"
#             memory: "300Mi"
#             ephemeral-storage: "1Gi"
#         evictionHard:
#             memory.available:  "200Mi"
#             nodefs.available: "10%"
#         featureGates:
#             RotateKubeletServerCertificate: true # has to be enabled, otherwise it will be disabled

# #private ondemand
#   - name: public-ondemand-t3-small-ng
#     ami: Ubuntu2004
#     instanceType: m5.xlarge
#     desiredCapacity: 10
#     minSize: 0
#     maxSize: 10
#     volumeSize: 80
#     labels:
#       my-cool-label: pizza
#     spot: true

# #private spot
#   - name: ng-2-builders
#     ami: Ubuntu2004
#     instanceType: m5.2xlarge
#     desiredCapacity: 2
#     volumeSize: 100
#     privateNetworking: true
#     subnets:
#       - subnet-0c5e27b6fc964ee15
#       - subnet-050ae6cf92c673cfe